load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "ImageLib",
		srcs = ["Image.cpp"],
    hdrs = ["Image.hpp"],
    deps = ["//activity-1/src/lib/Pixel:PixelLib"],
    visibility = ["//visibility:public"],
)